### ISSUE TITLE
how to view input password on evil twin?

### ISSUE THREAD

**Issue by smoochiee** [DX4GREY/esp8266_wifitools#3]

**Comment by DX4GREY** [comment]
On fs manager tab

**Comment by smoochiee** [comment]
> Open fs manager on the webserver with the web address http://192.168.4.1/fsmanager.html 

Not showing password when eviltwin attack done..![IMG_20240117_010524.jpg](https://github.com/DX4GREY/esp8266_wifitools/assets/30816448/ae063037-7d68-4f85-a658-e9d0bea60a70)

**Comment by smoochiee** [comment]
![IMG_20240117_010708.jpg](https://github.com/DX4GREY/esp8266_wifitools/assets/30816448/21f3d2dc-5cd7-4b71-b693-ec25c0669ba4)

![IMG_20240117_010716.jpg](https://github.com/DX4GREY/esp8266_wifitools/assets/30816448/3bdef277-9ea0-4068-bff1-ef23c4991943)

![IMG_20240117_010835.jpg](https://github.com/DX4GREY/esp8266_wifitools/assets/30816448/14b5b8b9-5f6f-4df6-b300-35cb4c38031e)

Where is the password log?

**Comment by DX4GREY** [comment]
The technical thing is that when the victim enters the password it will validate whether the password is correct, if so. That's right, the evil twin will be turned off and the password will be saved

**Comment by DX4GREY** [comment]
![Screenshot_2024-01-17-08-58-45-208_com.android.chrome.jpg](https://github.com/DX4GREY/esp8266_wifitools/assets/139307763/830a12e3-8d68-4931-9834-75a59168b39b)

This is a screenshot when the password is entered

**Comment by DX4GREY** [comment]
> > Open fs manager on the webserver with the web address http://192.168.4.1/fsmanager.html 
> 
> Not showing password when eviltwin attack done..![IMG_20240117_010524.jpg](https://github.com/DX4GREY/esp8266_wifitools/assets/30816448/ae063037-7d68-4f85-a658-e9d0bea60a70)
> 
> 

Tomorow i update the firmware

**Comment by smoochiee** [comment]
> > > Open fs manager on the webserver with the web address http://192.168.4.1/fsmanager.html 
> > 
> > Not showing password when eviltwin attack done..!
> > 
> > 
> 
> Tomorow i update the firmware

New update still not showing log

**Comment by smoochiee** [comment]
> > > Open fs manager on the webserver with the web address http://192.168.4.1/fsmanager.html 
> > 
> > Not showing password when eviltwin attack done..!
> > 
> > 
> 
> Tomorow i update the firmware

Can you add captive portal?like facebook phishing
